source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'pg'
gem 'devise', '~> 3.4.1'
gem 'font-awesome-rails'
gem 'protected_attributes'
gem 'twitter-bootstrap-rails'
gem 'bootstrap-sass'
# gem 'inline_svg'
gem 'haml'
gem 'erb2haml'
gem 'ckeditor'
gem 'redcarpet'
gem 'coderay'
gem 'gibbon'
gem 'figaro'

group :development, :test do
  gem 'mailcatcher'
  gem 'byebug'
  gem 'faker'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
